- README.md
- buildkite/client.go
- buildkite/provider.go
- buildkite/provider_test.go
- buildkite/resource_agent_token.go
- buildkite/resource_pipeline.go
- buildkite/util.go
> Improve documentation

- buildkite/resource_pipeline.go
Pipeline deletion was implemented with Buildkite REST API instead of GraphQL because of lacking of deletion mutation for pipeline. Buildkite has since added this missing feature.
* Use GraphQL to perform pipeline deletion
Fixes #56
> Update DeletePipeline() with GraphQL implementation

- .github/workflows/release.yml
- .goreleaser.yml
Copy step from the terraform registry docs: https://www.terraform.io/docs/registry/providers/publishing.html
Resolves #57
> Improve release process

- LICENSE.md
- README.md
> Update README and LICENSE

- .buildkite/pipeline.yml
- .github/dependabot.yml
- Dockerfile
- Makefile
- docker-compose.yml
- main.go
nothing fancy yet, just checking go fmt, go test and confirming that it all compiles.
> add the beginnings of a Buildkite pipeline

- README.md
* list the versions of terraform we'll support (0.13)
* reframe the we we link to the reference docs hosted by the terraform registry
* remove the duplicate release instructions section
Closes #75
> a few tweaks to the README

- .goreleaser.yml
So that I could use this provider on Linux ppc64le :)
> Build for PowerPC 64 LE

- buildkite/resource_agent_token.go
- buildkite/resource_pipeline.go
- buildkite/resource_pipeline_schedule.go
- buildkite/resource_team.go
Blocked by #100 and #103. I'm not keen to merge this until we have basic acceptance tests in place to detect regressions.
While working on #106 I noticed that v2 of the terraform sdk has deprecated the Create/Read/Update/Delete properties of the schema.Resource struct in favour of new properties that support passing context.
I thought I'd bite the bullet and just make the change everywhere so all current resources are a good model for adding new resources in the future.
Note that we only updated to v2 of the sdk in #89 ~3 weeks ago, so this deprecation only appeared for us recently.
I haven't made an effort to use the new context instances to improve the way timeouts are handled when we query the graphql API. That could be worth exploring in the future.
> stop using deprecated part of the terraform sdk API

- CHANGELOG.md
- README.md
- docs/index.md
* Changelog
* the version number used in example docs
/cc @chloeruka
> prep for a 0.2.0 release

- README.md
@chloeruka and I just released v0.3.0 and discovered these docs are slightlywrong.
> update docs for the release process

- docs/resources/pipeline.md
These parameters were displayed listed twice.
> Remove duplicate documentation entries

- docs/resources/pipeline.md
Support for these was added in PR #157, and full docs are available at https://buildkite.com/docs/pipelines/conditionals#conditionals-in-pipelines
> Add docs for the new filter_condition and filter_enabled properties

- .buildkite/steps/release.sh
This was tested locally and resolves issue #185 
Locally bin folder was created for m1 mac
> feat: :arrow_up: GoReleaser 0.157.0 -> 1.7.0

- buildkite/resource_pipeline.go
- buildkite/resource_pipeline_test.go
> add support for tags to buildkite terraform provider

- buildkite/resource_pipeline.go
- buildkite/resource_pipeline_test.go
This adds an `allow_rebuilds` property to the schema.  
It resolves #187
> Add allow rebuilds to pipeline resource

- buildkite/resource_pipeline.go
- buildkite/resource_pipeline_test.go
This fixes the issue with missing mutation arguments when also using clusters
> Add allowRebuilds to cluster mutations

- .buildkite/pipeline.yml
- .buildkite/steps/annotate.sh
- Dockerfile
- Makefile
- docker-compose.yml
- SUP-191 Add tparse for nicer test output
- SUP-191 Generate coverage and parse with tparse
- SUP-191 Create annotation from test output
> SUP-191 Generate test coverage

- .github/dependabot.yml
So they get noticed by someone
> Add a reviewer to dependabot PRs

- buildkite/resource_pipeline.go
- buildkite/resource_pipeline_test.go
- docs/resources/pipeline.md
- tf-proj/main.tf
The pipeline settings don't currently support setting default and maximum timeouts, but wait, now they do!
- Added 2 new fields to the struct for timeouts
- Added timeout settings to the main TF file
- Added timeouts to the GraphQL call in all necessary functions
- Added a test to check timeouts are set
> Add support for timeout settings.

- buildkite/util.go
- buildkite/util_test.go
> SUP-770 Fix panic in GetOrganizationID

- CHANGELOG.md
- README.md
- buildkite/resource_pipeline.go
Clean slate for work to commence before releasing updates
> Pipelines resource Computed/Default nil values reversion

- .github/PULL_REQUEST_TEMPLATE/new_feature.md
I think it might be a good idea to add entries to the changelog with each feature PR created so that the release process is a little easier and the changelog can just have some minor tweaks added
> Add another checkbox to PR templates

- CHANGELOG.md
- README.md
- docs/index.md
> Release v0.19.0

- CHANGELOG.md
- buildkite/data_source_meta_test.go
- buildkite/data_source_pipeline_test.go
- buildkite/data_source_team_test.go
- buildkite/provider.go
- buildkite/provider_test.go
- buildkite/resource_agent_token_test.go
- buildkite/resource_organization_settings_test.go
- buildkite/resource_pipeline_schedule_test.go
- buildkite/resource_pipeline_test.go
- buildkite/resource_team_member_test.go
- buildkite/resource_team_test.go
- main.go
> SUP-1072 Create new provider using framework plugin

- CHANGELOG.md
- README.md
- docs/index.md
Our Cluster, Cluster Queue and Cluster Agent Token release
> Release v0.20.0

- .github/CODEOWNERS
- CHANGELOG.md
- buildkite/data_source_organization.go
- buildkite/data_source_organization_test.go
- buildkite/provider.go
- buildkite/resource_agent_token.go
- buildkite/resource_cluster_agent_token.go
> Migrate organization datasource to plugin framework

- CHANGELOG.md
- buildkite/data_source_meta.go
- buildkite/provider.go
> SUP-1063 Convert meta datasource to framework

- CHANGELOG.md
- buildkite/generated.go
- buildkite/graphql/cluster_agent_token.graphql
- buildkite/graphql/node.graphql
- buildkite/resource_cluster_agent_token.go
- buildkite/resource_cluster_agent_token_test.go
Reverts buildkite/terraform-provider-buildkite#322
> Revert "Conversion of Cluster Agent Token resource to node GraphQL query"

- .goreleaser.yml
- CHANGELOG.md
- terraform-registry-manifest.json
- Add a manifest file for easier compatibility pickup
- Update CHANGELOG for manifest
- [-] `docs/` updated
- [-] tests added
- [-] an example added to `examples/` (useful to demo new field/resource)
> Add Terraform manifest.json file to root

- .goreleaser.yml
- CHANGELOG.md
- README.md
- docs/index.md
Turning this into a `v0.21.1` release PR
> Fix: goreleaser and Terraform manifest

- CHANGELOG.md
- README.md
- buildkite/resource_pipeline_schedule.go
- docs/index.md
> Set pipeline_schedule enabled=true

- CHANGELOG.md
- README.md
- docs/index.md
> Release prep for v0.22.0

- CHANGELOG.md
- README.md
- docs/index.md
> Release v0.24.0

- CHANGELOG.md
- buildkite/provider.go
- buildkite/resource_pipeline.go
- docs/index.md
- docs/resources/pipeline.md
> Move archive pipeline config to provider

- CHANGELOG.md
- README.md
- docs/index.md
> Release v0.25.0

- CHANGELOG.md
- buildkite/resource_pipeline.go
- buildkite/resource_team.go
- buildkite/resource_test_suite.go
- buildkite/resource_test_suite_test.go
- internal/planmodifier/use_state_if_unchanged.go
- internal/planmodifier/use_state_if_unchanged_test.go
> SUP-1388 Implement planmodifier.String for slugs

- CHANGELOG.md
- README.md
- docs/index.md
> Release 0.26.0

- CHANGELOG.md
- buildkite/resource_pipeline_team.go
- buildkite/resource_pipeline_team_test.go
> SUP-1399: Add retry to pipeline team resource

- CHANGELOG.md
- buildkite/resource_pipeline.go
> SUP-1361: Add timeouts to pipeline resource api

- CHANGELOG.md
- buildkite/data_source_cluster_test.go
- buildkite/provider_test.go
- main.go
- terraform-registry-manifest.json
> SUP-1370 Update to protocol v6

- CHANGELOG.md
- buildkite/data_source_cluster_test.go
- buildkite/provider.go
- buildkite/resource_agent_token_test.go
- buildkite/resource_cluster_agent_token_test.go
- buildkite/resource_cluster_queue_test.go
- buildkite/resource_cluster_test.go
- buildkite/resource_pipeline_schedule_test.go
- buildkite/resource_team_member_test.go
- buildkite/resource_team_test.go
- buildkite/resource_test_suite_team_test.go
- buildkite/resource_test_suite_test.go
- docs/index.md
> SUP-1395 Change timeouts to nested attribute

- CHANGELOG.md
- buildkite/resource_cluster_queue.go
> SUP-1492 Fix cluster queue description pointer

- CHANGELOG.md
- buildkite/provider.go
- buildkite/resource_pipeline.go
> SUP-1514 Change boolean flag to pointer

- CHANGELOG.md
- docs/data-sources/signed_pipeline_steps.md
> Update docs and changelog for release

- CHANGELOG.md
- buildkite/resource_pipeline_schedule.go
- buildkite/resource_pipeline_schedule_test.go
> SUP-1608 Pipeline schedule env escaping

- CHANGELOG.md
> Update changelog for release 1.2.0

- CHANGELOG.md
Resolved Organization resource allowed API IP address persistance and pipeline schedule `enabled` setting (more for the disabling of a schedule) through its respective mutation
> v1.3.0 Release

- .buildkite/pipeline.yml
- .golangci.yaml
- CHANGELOG.md
- Makefile
- buildkite/client.go
- buildkite/data_source_meta_test.go
- buildkite/resource_cluster_queue.go
- buildkite/resource_organization_banner.go
- buildkite/resource_organization_test.go
- docker-compose.yml
ci: Add support for golangci-lint
> SUP-1696: Add golangci-lint 

- CHANGELOG.md
- buildkite/resource_pipeline.go
> Update state upgrade functionality

- CHANGELOG.md
No change to `README` or `docs/` required.
> Release 1.5.1 - Update go-pipeline version

- .buildkite/pipeline.release.yml
- .buildkite/pipeline.yml
- CHANGELOG.md
- README.md
> Prep release 1.6.0

- .buildkite/pipeline.release.yml
- .buildkite/steps/release.sh
- docker-compose.yml
> Use new env vars for gpg key

- .github/CODEOWNERS
Adding myself to the CODEOWNERS to be able to approve and work on Pull Requests
> chore: Add tomowatt to CODEOWNERS

- CHANGELOG.md
> Release 1.10.0 - Improve handling of steps and changing outside TF

- buildkite/resource_cluster_queue.go
Fixes https://github.com/buildkite/terraform-provider-buildkite/issues/533
> Fix nil reference error when err may be nil

- CHANGELOG.md
> Release 1.10.1 - Fixes

- .github/ISSUE_TEMPLATE/feature_request.md
feat: Add a feature request issue template
No additions necessary.
> Adding a feature request template for better issue management/submission

- CHANGELOG.md
> Release 1.10.2 - More Fixes

- .github/CODEOWNERS
OK, this one is actually kind of sad.
Thanks to @jradtilbrook for everything that he's done with this provider. We'll care for it with love 💚
> Remove Jarryd from CODEOWNERS

- CHANGELOG.md
> Release 1.11.0 - Cluster queue improvements

- CHANGELOG.md
> Release 1.12.0 - Organization Rules Release

- CHANGELOG.md
I'd like to get this out to close off an escalation.
> Propose v1.13.0

- CHANGELOG.md
I've also included @petetomasik's two commits in the changelog for this release 👍
> Propose `v1.13.1`

- buildkite/resource_cluster_queue.go
Fix casing bug that prevents creating hosted queue with XL mac instance shape.
> Fix hosted agents Mac XL instance casing

- CHANGELOG.md
>  release/v1.15.5

- buildkite/resource_cluster_queue.go
- buildkite/resource_cluster_queue_test.go
Fixes https://github.com/buildkite/terraform-provider-buildkite/issues/870
> SUP-3312: Ensure hosted agent configuration is imported

- CHANGELOG.md
- buildkite/resource_cluster_queue.go
* bug: adds missing MacInstanceXLarge to list of Valid Instance Types
> SUP-3550: Refactor Hosted Instance Types for Maintenance

- docs/resources/pipeline.md
- examples/resources/buildkite_pipeline/resource.tf
Update Resources.tf file to include creation of Github webhooks
> update buildkite_pipeline docs

- .buildkite/pipeline.yml
- .github/dependabot.yml
- .golangci.bck.yaml
- .golangci.yaml
- buildkite/data_source_team.go
- buildkite/resource_organization_rule.go
- go.mod
- Add the team to Dependabot config so that we don't see warnings when a team memer leaves the team
> 🧹 General housekeeping

- CHANGELOG.md
> docs: Update CHANGELOG for v1.20.0

- buildkite/resource_pipeline.go
- docs/resources/pipeline.md
https://buildkite.com/resources/changelog/289-gitlab-dot-com-commit-status-support/
> feat(docs): add GitLab to list of platforms supporting commit statuses

- CHANGELOG.md
> Release v1.22.1

- .buildkite/pipeline.yml
- CHANGELOG.md
chore: add ossf scanning to repo
> Add OSSF scan to TF provider

- CHANGELOG.md
- buildkite/data_source_registry.go
- buildkite/data_source_registry_test.go
- buildkite/resource_agent_token_test.go
- buildkite/resource_cluster_agent_token_test.go
- buildkite/resource_cluster_queue_test.go
- buildkite/resource_cluster_test.go
- buildkite/resource_pipeline.go
- buildkite/resource_pipeline_schedule_test.go
- buildkite/resource_pipeline_template_test.go
- buildkite/resource_pipeline_test.go
- buildkite/resource_team_member_test.go
- buildkite/resource_team_test.go
- buildkite/resource_test_suite_test.go
- buildkite/util.go
- go.mod
- go.sum
chore(resource_pipeline): warn on `plan` when a pipeline of the same name exists
Fixes https://github.com/buildkite/terraform-provider-buildkite/issues/564
> warn on plan for duplicate pipeline name
