buildkite/terraform-provider-buildkite

buildkite/resource_pipeline.go
Thank you for your work on this provider plugin, @jradtilbrook! Really appreciate it.
Made my job a lot easier 🙂
I noticed that setting the default branch wasn't supported yet, so I implemented that. Empty default branch means all branches, so I tested `default_branch = ""` (which is also the default) and that works without problems.
Build skipping fields were recently added to the GraphQL API (https://forum.buildkite.community/t/feature-parity-for-pipeline-creation-between-graphql-and-rest-apis/600/3), so I implemented them too.
=> Add support for default branch and build skipping

README.md, buildkite/resource_pipeline.go
As issue #48 points out, teams are only a thing on paid plans. This makes the team block optional and updates the readme including a warning about non-admin users creating a pipeline without a team. I'd imagine this doesn't error on a free plan but does error on a paid plan.
Resolves #48
=> Make pipeline teams optional

README.md, buildkite/resource_pipeline.go
This PR would allow users to configure pipeline-level branch configuration
Because there is no support to update this attribute in GraphQL API. The implementation is done via the RESTful API. It comes with a cost... that is an extra HTTP call after the GraphQL API call just for updating one attribute.
=> Add branch_configuration arg

README.md
* Added download instructions for OSX.
* Removed one example since it did not have the `team` argument which is required for the `buildkite_pipeline` resource.
=> README.md: added download instructions

docs/resources/agent_token.md
to: @jradtilbrook 
#62 added documentation, but there is a whitespace encoding issue. Can be seen here: https://registry.terraform.io/providers/jradtilbrook/buildkite/latest/docs/resources/agent_token
* Fixed whitepsace around `Import` within the markdown
<details>
<summary><code>Visible bug</code></summary>
</details>
=> Fix character encoding in agent_token docs

docs/resources/pipeline.md
I noticed that the pipeline resource supports the following variables but wasn't documented.
=> Adds missing pipeline arguments to documentation

go.mod, main.go
This ensures building the plugin uses the code in this repo:
$ go build -o buildkite-terraform .
=> Update go module name to use the new home on GitHub

README.md, docs/index.md
This detail is already in the provider docs in the Argument Reference, however I didn't notice them and ended up looking in the code first.
I assume we'll want to mostly point to the docs hosted by the registry as the best place to learn how to use the provider, but I reckon the API token requirements are important enough to also list in the README.
=> Expand the README to mention the scopes required on the API token

.github/CODEOWNERS
Multiple engineers at Buildkite will support this repo now, no need for every PR to dob @jradtilbrook in for reviews
=> remove CODEOWNERS

.buildkite/pipeline.release.yml, .buildkite/steps/release.sh, .gitignore, .goreleaser.yml, docker-compose.yml
Releasing to Github requires a private GPG key and GitHub token, so we run the pipeline in a different context to the main build pipeline.
This is a  slightly awkward process compared to our normal create-a-gh-release pipeline because terraform recommend using goreleaser and I wanted to follow their golden path to avoid any surprises.
I'm reasonably confident this will work great, however so far I've only run it in dry mode. I'll do a for-reals test after it merges to master.
=> Add a release pipeline

buildkite/provider.go, buildkite/resource_pipeline_schedule.go, docs/resources/pipeline_schedule.md
Closes #58
Example: 
```hcl-terraform
resource "buildkite_pipeline_schedule" "my-schedule" {
pipeline_id = buildkite_pipeline.<resource_name>.id
cronline    = "0 *  * * *"
label       = "My schedule"
}
```
I did some manual testing locally and it works fine, however, this is the first time I'm writing `golang` code so some obvious bugs are probably still there.
Also, I'm not sure how to write automated tests for this...
TODOs:
=> feat: pipeline_schedule resource type

buildkite/resource_pipeline_test.go
This resource had no acceptance tests, and we were nervous about the risk of regressions.
This adds a few initial test cases:
* creating a pipeline with only the required attributes set
* creating a pipeline with all attributes set
* updating a pipeline
* importing an existing pipeline
Pipeline deletion is tested implicitly when the terraform testing sdk cleans up after a test.
We assume there's potential for more tests that exercise specific combinations (for example, exposing this teams related bug in pipeline creation #84), but this is a good start
=> Add some aceptance tests for the pipeline resource

README.md
There are some [implications for enabling Teams](https://buildkite.com/docs/pipelines/permissions) in an organization, and in order to support useful Teams features in this Terraform provider, we should acceptance test them. Our current acceptance tests function without Teams enabled in our test organization (`buildkite-terraform-provider-test-org`) and it's a barrier at the moment for writing further acceptance tests that consider them. Should we consider a broad recommendation that users enable Teams and switch it ON for all acceptance tests?
- Maintaining multiple sets of acceptance tests to support the case of teams not being enabled adds significantly to our overall test coverage requirements
- Supporting gear such as a secondary organization or function to toggle teams for tests …
=> Add statement regarding teams expectation

buildkite/data_source_pipeline.go, buildkite/data_source_pipeline_test.go, buildkite/provider.go, docs/data-sources/pipeline.md, docs/resources/pipeline.md
This adds a data source for fetching the properties of a single pipeline. The pipeline is specified using a slug, available in the
pipeline URL on buildkite.com.
This could be particularly useful for folks who want to lookup the webhook URL and set it on a GitHub repo (using the  GitHub terraform provider).
Closes #93
=> Add a pipeline data source

.buildkite/steps/release.sh
[v0.156.x adds support for compiling a native binary for Apple Silicon systems](https://github.com/goreleaser/goreleaser/releases/tag/v0.156.2):
> GOOS=darwin GOARCH=arm64 was ignored before this release, since it was
> a build for iOS that most people didn't care about and required more
> than just go to build.
>
> On Go 1.16, this target is now the macOS on Apple Silicon. GoReleaser
> v0.156.0+ is built for Go 1.16+ and will try to build the darwin arm64
> target if the config allows it
This is hard to test, we might just have to wait until we're ready to make an actual release.
Closes #94 (probably).
=> update goreleaser from v0.149.0 to v0.157.0

buildkite/resource_pipeline_schedule.go, buildkite/resource_pipeline_schedule_test.go
This resource also lacked acceptance tests, so in order to guard against regressions we have added the following simple acceptance tests:
* creating a schedule (with only the required attributes)
* updating a schedule (e.g. changing its cronline)
* importing a pipeline schedule
This work required the addition of UUID to the pipeline schedule resource schema. The UUID is used to assemble the slug of an existing pipeline schedule.
=> Add acceptance tests for pipeline schedule

buildkite/resource_team.go, buildkite/resource_team_test.go
This is one of the resources that does not yet have acceptance tests associated with it. In order to guard against regressions, I have added the following tests:
* creating a team (with only the required attributes)
* updating a team (changing its name, description and visibility)
* importing a team
During this work I discovered an error in importing teams. In order to resolve this, I added the DefaultMemberRole value which was present in the schema to the TeamNode struct, and added a mapping to updateTeam, so this PR doubles as a bugfix for importing teams.
=> Add acceptance tests for teams

.buildkite/pipeline.yml
Because we use named resources on Buildkite in our acceptance tests, when multiple steps of this type run in parallel (e.g. if we have multiple merges at the same time) it can cause the tests to fail when they try to create resources with the same tokens in the test organisation. In order to fix this, I've set the concurrency limit to 1 on a new `terraform-provider-acceptance-tests` concurrency group.
This won't fix the scenario of a developer running the acceptance tests locally at the same time as a build happens to run them too, but the scenario is relatively unlikely and we can just retry it. If this repository gets significantly more active we can revisit this and try to fix it by giving resources unique per-run names.
=> Add concurrency limit to acceptance test steps

buildkite/provider_test.go, buildkite/resource_agent_token_test.go, buildkite/resource_pipeline_schedule_test.go, buildkite/resource_pipeline_test.go, buildkite/resource_team_test.go
Resolve #110 by adding concrete cleanup checks for resource destroy and acceptance tests to all resources to ensure that Terraform can generate a plan to remove a resource (except agent tokens, as they are revoked rather than destroyed).
`testAccCheck*ResourceDestroy` unfortunately can't easily be tested unless Terraform hadn't cleaned up the resource. Hopefully, all the same, this gives us some good meaningful logging if something does break in the future. Plus we shedded TODOs.
=> Ensure all resources are destroyed after tests

buildkite/resource_pipeline_schedule_test.go
pipeline schedules are not permitted to run more frequently than every 10 minutes.
This test was updating the cronline to `* 0 * * *`, which is "every minute during hour 0". Apparently our server side validation only
detects that as an error when the update runs during UTC hour 0, so [this test fails when run during UTC hour 0](https://buildkite.com/buildkite/terraform-provider-buildkite-main/builds/43#c6ca85d2-9311-43c8-91a0-9290460242c0).
The test now updates the cronline to "daily at 1:00 UTC".
=> adjust cron line we use in pipeline_schedule update test

buildkite/resource_pipeline.go
For Buildkite organizations with teams enabled, it's possible for non-admins to create pipelines within their own teams.
However, it only works if the team is included in the `pipelineCreate()` mutation. For a non-admin graphql token, `pipelineCreate() `will return an error if the input includes no teams.
The existing code was calling `pipelineCreate() `with no teams, and then following up with a `teamPipelineCreate()` mutation to apply the teams. We never got to the follow up though, because the initial `pipelineCreate()` was failing.
This merges the two steps so the initial `pipelineCreate()` includes teams. Once the pipeline has been created, team management is still done independently of the rest of the pipeline. That should be fine though, it's only `pipelineCreate()` that requires …
=> Adjust pipeline creation so it works for non-admins

.buildkite/pipeline.yml, Makefile, buildkite/resource_pipeline_schedule_test.go, buildkite/resource_pipeline_test.go
In PR #112 we fixed the pipeline resource so it can be created and updated by non-admin API tokens.
To prevent regressions, this adds a new acceptance test step to the build pipeline that will run only the subset of acceptance tests that will work with a non-admin API token.
Non-admins can manage pipelines and pipeline schedules, but only if the pipeline belongs to a team where the user is a team maintainer.
Before this we had no acctests with teams declared on a pipeline, so none of them would work for non-admins. This has added a couple of basic tests that use teams.
The new tests will also run in the normal acctest step (using an admin token), which is a nice bonus.
=> Add build step for subset of acctests that will work with a non-admin API token

buildkite/resource_pipeline_schedule_test.go
We accidentally left a hard coded slug in here, which means this test fails when run against any other organization. That wasn't our intention - all contributors should be able to run the tests against their own test organization.
Fixes #121
=> remove hard coded org slug from the PipelineSchedule acceptance tests

buildkite/resource_pipeline.go
Added `Compute: true` to all pipeline resource attributes that has default values set by Buildkite (this fixes a lot of warnings that you can see running terraform apply for a with TF_LOG=debug env variable, like:
```
2021/03/09 17:41:15 [WARN] Provider "registry.terraform.io/buildkite/buildkite" produced an unexpected new value for buildkite_pipeline.test, but we are tolerating it because it is using the legacy plugin SDK.
The following problems may be the cause of any confusing errors from downstream operations:
- .branch_configuration: was null, but now cty.StringVal("")
```
This is a spin off from https://github.com/buildkite/terraform-provider-buildkite/pull/123
=> Use 'Computed: true' for attributes that are initialized on backend

README.md, buildkite/client.go, buildkite/provider.go, buildkite/resource_pipeline.go, buildkite/resource_pipeline_test.go, docs/index.md, docs/resources/pipeline.md
1. `provider_settings` block is `Optional` for backward-compatibility reasons. Also it is `Computed` (so default values are set by buildkite backend, while it is still possible to override the values by specifying custom values for each property in terraform resource configuration).
1. all `provider_settings` are provider-agnostic (the user should know which attributes are supported by the provider they use)
- to disable build triggers:
```hcl
provider_settings {
trigger_mode = "none"
}
```
- trigger builds for tags:
```hcl
provider_settings {
trigger_mode = "code" # default value, so could be omitted (not recommended though) 
build_tags = true
}
```
1. Removed `ReadPipeline` calls at the end of `CreatePipeline` and `UpdatePipeline` methods, as we already set attribute values for …
=> Add provider_settings to pipeline resource

buildkite/data_source_meta.go, buildkite/data_source_meta_test.go, buildkite/provider.go, docs/data-sources/meta.md
This adds a new data source for listing the IP addresses that Buildkite uses to send webhooks and other external requests (like commit status API calls to GitHub Enterprise and BitBucket Server).
It takes no parameters, and can be used like this:
```hcl
data "buildkite_ip_ranges" "ips" { }
output "cidrs" {
value = data.buildkite_ip_ranges.ips.webhook_ips
}
```
This is intended to be used in other terraform projects to dynamically set firewall and ingress rules to allow traffic from Buildkite. For customers that use AWS, that might look like this:
```hcl
data "buildkite_ip_ranges" "ips" { }
resource "aws_security_group" "from_buildkite" {
name = "from_buildkite"
ingress {
from_port        = "*"
to_port          = "443"
protocol         = "tcp"
cidr_blocks      = …
```
=> Add buildkite_ip_ranges data source

.github/dependabot.yml
We don't need to update to every new docker image with the same version, we're mostly interested in getting the golang version bumps. Getting them only once per month is fine.
=> drop dependabot frequency from weekly to monthly

docs/resources/pipeline.md
This property is present in the GitHub example earlier in the document
but not explicitly documented.
It's commonly used when setting up pipelines used to validate a specific
branch and pull request based workflows.
=> Document build_branches provider setting

.gitignore, buildkite/resource_pipeline.go, docs/resources/pipeline.md, examples/main.tf, tf-proj/main.tf
Extended the PipelineExtraInfo so that it includes the badge_url as a readonly property. So that it can be returned as an output attribute when a new pipeline is created. 
Resolves [Issue](https://github.com/buildkite/terraform-provider-buildkite/issues/148)
=> feat: extended the Pipeline Extra Info to include the badge_url as an output

docs/resources/agent_token.md, docs/resources/pipeline.md, docs/resources/pipeline_schedule.md, docs/resources/team.md
In #117 @keith noticed our docs weren't documenting the ID attribute of some resources. While fixing that, I noticed a handful of other read-only resource attributes that weren't documented as well.
=> Fill in docs for some missing attributes

buildkite/resource_pipeline_test.go
A very small addition to the tests. 
While reviewing #151 I noticed we weren't confirming that the `webhook_url` property of the pipeline resource was being set correctly.
Now we are.
=> expand pipeline resource acceptance test to confirm webhook_url is set correctly

buildkite/resource_pipeline.go
In #117 @keith reported that we return a particularly unhelpful error to users when a pipeline references a team slug that doesn't exist:
resource "buildkite_pipeline" "repo2" {
name = "repo2"
repository = "git@github.com:org/repo2"
steps = file("./steps.yml")
team {
slug = "not valid"
access_level = "READ_ONLY"
}
}
The error was:
> Error: No ID was supplied
I'm not 100% sure this error handling is where the error @keith saw was from, but it seems pretty likely. Even if it's not, this seems like a good change to make.
The Printf() is only visible to users when debug mode is on, which will almost never be true. Moving that message to an error that will be displayed to the user (and can be searched in this codebase while debugging) seems like a win.
=> Return a better user visible error when pipeline references an unrecognised team slug

buildkite/resource_pipeline.go, buildkite/resource_pipeline_test.go
https://github.com/buildkite/terraform-provider-buildkite/issues/149
Add the filter_enabled and filter_condition  properties to pipeline module.
https://buildkite.com/docs/apis/rest-api/pipelines#provider-settings-properties
=> Add filter_enabled and filter_condition properties

docs/resources/pipeline.md
The actual property is `badge`, this just looks like a misspelling.
https://github.com/buildkite/terraform-provider-buildkite/blob/7117eb3866171b60189f42c65651668557da0458/buildkite/resource_pipeline.go#L257-L260
=> Fixes typo in pipeline Docs

docs/resources/pipeline.md, examples/steps.yml
I was setting up my terraform integration and noticed I was missing the `pipeline` subcommand with the steps I'd taken from the docs.
Hope this helps.
=> Examples and documentation fix: pipeline subcommand was missing

buildkite/resource_pipeline.go, buildkite/resource_pipeline_test.go, docs/resources/pipeline.md
Add the `build_pull_request_labels_changed` property to the pipeline module.
This property is written in the example response of  https://buildkite.com/docs/apis/rest-api/pipelines#create-a-yaml-pipeline.
=> Add the build_pull_request_labels_changed property

buildkite/provider.go, buildkite/resource_team_member.go, buildkite/resource_team_member_test.go, docs/resources/team.md, docs/resources/team_member.md
This PR adds the `buildkite_team_member` resource to manage connecting organisation users to teams.
The basic stuff should work since I've tested it manually although I haven't written unit tests just yet.  
Since teams have a notion of "default role", the role attribute on this resource is optional. However, if you specify it, apply, then remove it and apply it will break. I think we need to store the teams default role or look it up for instances where the role is not supplied.
That leads to the following to do items:
=> SUP-106 Add `buildkite_team_member` resource

buildkite/resource_pipeline.go, docs/resources/pipeline.md
Add the `cluster_id` as optional argument to the pipeline resource.
The graphql `pipelineCreateInput` already takes `clusterId` as an input field, and `Cluster` is returned in the `PipelineNode` as well.
Note I was not able to run the acceptance tests locally, even off of the `main` `buildkite/terraform-provider-buildkite` branch. Local unit tests, build and `terraform plan` were successful, however.
Closes [issue 179](https://github.com/buildkite/terraform-provider-buildkite/issues/179).
🙇🏻‍♂️
=> Add cluster_id argument to pipeline resource

buildkite/data_source_team.go, buildkite/data_source_team_test.go, buildkite/provider.go, docs/data-sources/team.md
This PR adds a team data source that uses the team slug to look up the team.
I felt this would be useful for validating the team slug passed to the `pipeline` resource, because if an invalid team name is supplied it can cause the pipeline to be created with no team which then needs cleaning up by admins.
This is my first terraform provider change so I shamelessly copied from https://github.com/buildkite/terraform-provider-buildkite/pull/106 as suggested in #139. I'm open to whatever feedback you want to give, as well as commits directly to the branch :)
I compiled the provider as instructed in the README and ran  `terraform plan` for the following:
```hcl
data "buildkite_team" "this" {
slug = "everyone"
}
output "team" {
value = data.buildkite_team.this
}
```
This was the output:
``` …
```
=> Add team data source

.buildkite/pipeline.yml
This removes the conditional on the acceptance test steps so that we can run them for every PR. These are the critical tests that provide so much value and would rather have them automated than manual.
=> SUP-312 Build fork PRs

docs/resources/pipeline.md
`allow_rebuilds` was added with [this PR](https://github.com/buildkite/terraform-provider-buildkite/pull/193).
Adds documentation for `allow_rebuilds`.
=> Add allow_rebuilds documentation. Grammar.

.buildkite/pipeline.yml
Assume an IAM role that's been created specifically for this pipeline. It has only the permissions required by this pipeline, and can only be assumed via an OIDC token generated for this pipeline.
Also change to a Buildkite controlled version of the aws-ssm plugin.
=> tests: Assume an IAM role before fetching tokens from parameter store [PLT-555]

.github/dependabot.yml
Some of the direct and indirect dependencies in gomod are looking a bit out of date. This configures dependabot to occasionally bump them, but only up to 2 PRs at a time. We want to slowly keep them updated and avoid bitrot, without being overwhelmed by the rate of PRs.
=> enable dependabot for gomod

README.md
Added some context around using local plugins via setting overrides in the `.terraformrc` file.
=> Add documentation around plugin override for local dev

.buildkite/steps/annotate.sh
I'm not sure if it was originally intentional that it didn't error out early so that we could get the annotation and test analytics stuff still executed. But doing it that way has lost trust in the state of CI so failing fast is preferred
=> SUP-838 Ensure CI passes/fails correctly

.buildkite/steps/annotate.sh, buildkite/resource_pipeline.go, buildkite/resource_pipeline_test.go, docs/index.md, docs/resources/pipeline.md, examples/main.tf, tf-proj/main.tf
This came in as a request from Slack and seems like a reasonable ask given the authority that Terraform can have over an organisation.
- Add `delete_protection` as an option on a pipeline (defaults to `false`)
- Add tests around the `deletion_protection` config
- Add nice messaging for error when user tries to destroy pipeline with `deletion_protection` enabled
=> SUP-866 Add deletion protection for a pipeline

Dockerfile, Makefile, buildkite/client.go, buildkite/provider.go, buildkite/provider_test.go, buildkite/util_test.go, main.go
This sets the user agent for api client.
Using [Provider.UserAgent](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema#Provider.UserAgent) to set the header.
Also, this can now take a `version` coming from ldflags which is added as a suffix.
Rendered example:
```
Terraform/ (+https://www.terraform.io) Terraform-Plugin-SDK/2.0.3 buildkite/v0.14.0-1-g3539448
```
=> Set User-Agent header in client

.buildkite/pipeline.release.yml
After reconfiguring our Docker images to be retrieved via a pull-through cache we need to allow the release step (which runs on agents in a completely different AWS account) pull access to the cached golang images.
=> Allow release pipeline to pull from private ECR registry

buildkite/client.go, go.mod
In #256 we starting setting a custom User-Agent header on REST API calls, to help us understand the ways our API is used. It looks like this:
Terraform/ (+https://www.terraform.io) Terraform-Plugin-SDK/2.0.3 buildkite/0.15.0
This builds on that work and sets the same User-Agent on graphql API requests as well.
It drops the unnecessary use of golang.org/x/oauth2 to set a static bearer token header, and uses the [tripperware pattern](https://dev.to/stevenacoffman/tripperwares-http-client-middleware-chaining-roundtrippers-3o00) to set both headers we care about:
1. the static bearer token for auth
2. the user agent
The same http.Client is used for both REST and graphql, so we'll get identical behaviour on both APIs.
=> Set User-Agent header on both REST and graphql requests

buildkite/client.go, buildkite/provider.go, buildkite/resource_agent_token.go, buildkite/resource_pipeline.go, buildkite/resource_team.go, buildkite/util_test.go
To improve performance, move the retrieval of organization ID to the provider configuration/startup instead of each time it is required by a resource operation
=> SUP-819 Retrieve org id only once in provider configuration

Dockerfile
Update the terraform version used in CI to 1.4
This is implemented through multistage build for caching performance
=> SUP-820 Pull latest 1.4 version terraform from docker image

buildkite/resource_pipeline.go, buildkite/resource_pipeline_test.go
Amended the Pipeline resource's step parameter to be Optional with a default of `buildkite-agent pipeline upload` if not defined in a to-be-made pipeline resource
Utilising a pipeline.tf file like below:
```
resource "buildkite_pipeline" "terraform-bk-example" {
name = "terraform-bk-example"
repository = "git@github.com:james2791/terraform-bk-example.git"
default_branch = "main"
}
```
Pipeline resource creation
Pipeline creation with the default step:
Acceptance tests created (one with no default steps which gets filled, the other with steps defined) - running against my own org/API key
=> SUP-707: Pipeline resource's steps made optional, default pipeline upload step  

.buildkite/pipeline.yml
For consistency with other pipelines, we're prefixing all ENV var paths with the org slug in addition to the pipeline slug - note the `/buildkite` inserted into each path here.
=> Update the paths where we load environment variables from

README.md, docs/resources/pipeline.md
Added the latest (to be) provider version as the README's version pointer
Revised in the Argument Reference:
- `steps` to be Optional, and defaulting to `buildkite-agent pipeline upload` if not set in the TF schema
- `tags` added (SUP-906)
Branch build [passing](https://buildkite.com/buildkite/terraform-provider-buildkite-main/builds/361)
=> SUP-906/Fix: Adjustment of README version, Pipeline Argument Reference amendments

CHANGELOG.md, README.md
Bumping and aligning versions to the changelog with past history. Also prepping for the `v0.18.0` release
=> SUP-995: Changelog updates, v0.18.0 release prep

CHANGELOG.md, buildkite/resource_pipeline.go, docs/resources/pipeline.md
When creating a new pipeline in the UI, these settings default to on. We should have the terraform provider do the same thing.
The specific settings are:
And that maps to the `build_pull_requests`, `skip_pull_request_builds_for_existing_commits`, `build_branches`, `publish_commit_status`.
=> SUP-1043 Change default provider settings to match new pipeline

main.go
Changed the provider servers to be `v5` rather than `v6`. The former supports older versions of Terraform and doesn't break on `v1.x.x` anyway, so no reason to not use it. Especially if we aren't bumping to a major release.
[Issue](https://github.com/buildkite/terraform-provider-buildkite/issues/293) was raised where folks using `v0.14.1` couldn't use the Terraform provider due to a breaking change in updating the provider version; `v6` requires Terraform version `0.15.4` or higher.
If we are't willing to release a major version bump, we need to consider backwards compatibility as a **requirement**.
Changed the provider versions used to be of `v5` rather than `v6`. According to https://developer.hashicorp.com/terraform/plugin/framework/migrating/mux#mux-server-examples, we need to …
=> Support TF version < 0.15.4

.github/CODEOWNERS
- Add a CODEOWNERS file to improve alerting/remove need for requests/ensure PRs seen.
- Make it specifically the APAC team for now
=> Add CODEOWNERS file to automatically tag APAC folks

buildkite/resource_pipeline.go
Removed computed since this value should be known on creation.
Added default value to true since this is described in the docs to be true by default.
Fixes: https://github.com/buildkite/terraform-provider-buildkite/issues/307
=> Fixed default for allow_rebuilds on provider to match docs

CHANGELOG.md
Teams datasource PR linked and the Optional `slug` or `id` when using.
=> Changelog update prior to v0.21.0

buildkite/resource_cluster_test.go
It essentially means that tests can be run concurrently by multiple users locally and possibly removes the need for the concurrency group in CI if applied to all tests.
=> Initial roll out with Cluster resource tests

CHANGELOG.md, buildkite/resource_pipeline.go
Mark `deletion_protection` as `Deprecated` in favour of moving towards the use of [lifecycles](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle).
This enables us to continue to support the attribute for now, but gives warning to users that it's been deprecated. The deprecation `message` links to lifecycles.
=> Add deprecation warning. Update CHANGELOG.

README.md, buildkite/provider.go, docs/index.md
With the addition of the Test Suite resource in [v0.22.0](https://github.com/buildkite/terraform-provider-buildkite/compare/v0.21.2...v0.22.0), one's API access token that is used to interact with the provider needs to additionally have the `write_suites` scope for said API token to create/update and delete suites (interaction with the REST API)
=> Added note on write_suites API access token scope to README

CHANGELOG.md, README.md, buildkite/resource_test_suite.go, buildkite/resource_test_suite_test.go, docs/index.md
=> V0.23.0 release

CHANGELOG.md, buildkite/resource_pipeline.go, buildkite/resource_pipeline_test.go
=> SUP-1383 Fix teams block bug in v0.25.0

CHANGELOG.md, buildkite/resource_test_suite_test.go
fix (Test suite tests): [Randomising test suite names]
=> SUP-1392: Random test suite names in tests/t.Run() conversion

CHANGELOG.md, buildkite/resource_agent_token.go, buildkite/resource_agent_token_test.go
feat (Timeouts/Retries): Add timeouts (provider config set) and CRUD retries to the Agent token resource.
Also converted the tests with a `t.Run` to enable parallelism / set timeouts in test configuration (random agent token names with `accTest`)
=> SUP-1402: Agent token resource retries 

CHANGELOG.md, buildkite/resource_pipeline_test.go
=> SUP-1405: Fix dangling team resources created in tests

CHANGELOG.md, buildkite/client.go, buildkite/resource_test_suite.go, buildkite/resource_test_suite_team.go, buildkite/resource_test_suite_team_test.go, buildkite/resource_test_suite_test.go
feat (Timeouts/Retries): Add timeouts (provider config set) and CRUD retries to the Test suite and test suite team resources.
Also converted the Test suite team tests with `t.Run` to enable parallelism / set timeouts in test configuration. Both TS and TST have randomness enabled previously.
This PR also adjusts the Client's `makeRequest` function to returns errors with a `returned error` format line so that REST API requests can benefit from the rate limit/server error retry methods implemented.
=> SUP-1400: Test suite and test suite team (team suite) resource retries 

CHANGELOG.md, buildkite/resource_agent_token.go, buildkite/resource_cluster.go, buildkite/resource_pipeline_schedule.go, buildkite/resource_pipeline_team.go, buildkite/resource_team.go, buildkite/resource_team_member.go, buildkite/resource_test_suite.go, buildkite/resource_test_suite_team.go
refactor(Resource timeouts): Move to shared `util.go` retryContextError function
Implemented by [this](https://github.com/buildkite/terraform-provider-buildkite/pull/385) PR and moved to `util.go` in this [PR](https://github.com/buildkite/terraform-provider-buildkite/pull/388) - this change replaces the retry logic of all other resource retry logic (determining if the GraphQL/REST query is retryable or not based on the status code returned) using the common shared `retryContextError` function
=> retryContextError util resource switch

CHANGELOG.md, buildkite/resource_pipeline_test.go, docs/resources/pipeline.md, examples/main.tf
feat(Pipeline docs): Addition of `build_pull_request_ready_for_review` for a Pipeline's `provider_settings` configuration 
Missing attribute of `provider_settings` that the Pipeline's provider settings schema had implemented but was asked about via the forum, wasn't included in docs/tests or examples previously which I've added here!
=> Added `build_pull_request_ready_for_review` to pipeline resource docs/examples/tests

CHANGELOG.md, buildkite/provider.go, docs/guides/upgrade-v1.md, docs/index.md, templates/guides/upgrade-v1.md
I've had a play around with an automated test and manual test and can't actually get it to throw an error. It just removes the team block from state and is fine.
It leaves the team/pipeline relationship in place though so if switching over to buildkite_pipeline_team it will cause an error because the team is already present. I don't think that is something we can fix automatically for people though because it would mean removing the team which could break users workflows.
We'll need to outline how to upgrade in the docs for v1.0 so it doesn't cause an outage for them
=> SUP-1431 Upgrade path for pipeline teams

CHANGELOG.md, buildkite/resource_pipeline.go, buildkite/resource_pipeline_team_test.go, buildkite/resource_pipeline_test.go, docs/guides/upgrade-v1.md, docs/resources/pipeline.md, examples/resources/buildkite_pipeline/resource.tf, templates/guides/upgrade-v1.md
refactor(pipeline resource): Migration of `provider_settings` from a block to a nested attribute
This change converts the `provider_settings` block (pipeline schema version `0`) to a nested attribute (schema version `1` with Terraform Plugin Framework's `UpgradeState` functionality. With this change, there is only the schema version `0`->`1` upgrade, but can be added to the [StateUpgrader](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework@v1.4.0/resource#StateUpgrader) map specifying newer schema updates (with a corresponding prior versioned schema and state upgrade function)
Both tests written are using the `ExternalProviders` capability to create a pipeline with block `provider_settings` (one with default attributes, the other with set) - which both are upgraded to the …
=> SUP-1390: Provider Settings conversion to a nested attribute

CHANGELOG.md, buildkite/resource_pipeline.go, buildkite/resource_pipeline_test.go
=> Dont set provider_settings if not defined

CHANGELOG.md, buildkite/data_source_signed_pipeline_steps.go, docs/data-sources/signed_pipeline_steps.md
I made the typo, so mea culpa.
=> Fix a typo in the signed pipelines data source

buildkite/resource_pipeline.go, docs/resources/pipeline.md
Setting the pipeline option `skip_builds_for_existing_commits` on a pipeline which does not use a GitHub repository causes Terraform to fail. The error message says that the failure is caused by a bug in the provider, without any indication of how to fix it. I've added the GitHub restriction to the resource documentation.
See https://github.com/buildkite/terraform-provider-buildkite/issues/437
=> Document restriction 'skip_builds_for_existing_commits' pipeline option

buildkite/resource_team.go, docs/resources/team.md
The current MarkdownDescription for the Teams resource references the Cluster documentation.  This PR fixes the description of the resource and links to the appropriate part of the Buildkite docs.
=> Fix Teams resource documentation

docs/data-sources/pipeline_template.md, examples/data-sources/buildkite_pipeline_template/data-source.tf
Docs (Pipeline data source: Pipeline template data source docs format
Spacing on the pipeline template data source examples was indented a bit too much; reverted to 2 space indentation for consistency
=> SUP-1711: Pipeline template data source docs format

CHANGELOG.md, buildkite/resource_pipeline.go
The release for 0.27.1 has an issue where the default team ends up being included in the teams block in state and then failing verification from terraform. This adds checks for the default team so that it is not included in state
=> Ignore default team in teams block

CHANGELOG.md, buildkite/data_source_team.go, docs/data-sources/team.md, examples/data-sources/buildkite_team/data-source.tf
Docs (Team data source) : Team data source example/description tweak
Folks might get confounded on the mention of the team datasource's `id` or `slug` (within each's Markdown description) that they can  "`Use either ID or slug`" - and might use either attribute in stand for one-another, breaking their underlying `node`/`team` queries.
Small tweak to the descriptions/examples to make it more clear that its exclusive between the two attributes.
=> SUP-1877: Team datasource docs/example tweaks

CHANGELOG.md, buildkite/resource_pipeline.go
The graphql API returns an error when trying to query webhook URL after creation for security, however, the REST API will return an empty string if the token is not allowed. So it still returns a successful response.  
We can use this to resolve the webhook URL of a pipeline optimistially when reading the pipeline
Resolves #480.
=> SUP-1851 Get pipeline webhook from REST API

go.mod, go.sum
Currently the provider uses an older version of the go-pipeline package which has a bug where `wait:` steps don't parse. This is fixed in the latest version of the go-pipeline package. The provider should update to the latest version of the go-pipeline package to fix this issue.
=> Update go-pipeline version

CHANGELOG.md, buildkite/resource_pipeline_test.go
The error raised here happens  when setting  the `provider_settings` to null or omitting it from the configuration file and these changes to the terraform state file is applied.  Terraform is expecting `provider_settings` as null, but the provider applies values to the `provider_settings` by retrieving them from the actual infrastructure through api. Since the `provider_settings` default values are set at the infrastructure level, these values will always be reflected into the state file.
This is an expected behaviour. The `provider_settings` cannot be set to null when it already exists on the terraform state file as it is not a computed attribute. Our schema only defines it as `Optional` and not `Computed`.  However, we cannot set it to `Computed:true` since this will also mean that …
=> SUP-1906 Error on apply when provider_settings is omitted

.buildkite/steps/release.sh
The gpg key is stored in as ASCII armord format with new lines escaped, like:
MjAxMjMxMmFkZWZnMjIK\nOTMwNDA0MDRlZWVmYQo=
We need echo to process the escaped newlines before piping it to gpg, so gpg sees:
MjAxMjMxMmFkZWZnMjIK
OTMwNDA0MDRlZWVmYQo=
=> Fix importing of gpg key used for release signing

CHANGELOG.md
=> Release 1.7.0 - Expose key on default queue

.goreleaser.yml
- In our release we attempt to build Windows ARM64, but that's deprecated as of Go 1.17
Ref: https://goreleaser.com/deprecations/#builds-for-windowsarm64
=> Windows ARM64 is deprecated in GoReleaser

.buildkite/pipeline.yml, .buildkite/steps/release.sh, Dockerfile, Makefile
This change is primarily focused on the goreleaser configuration, which is updated as follows:
1. Remove the installation process and follow the pattern used to install terraform using docker copy, and a method
which will automatically cover other architectures such as arm64.
2. Ensure goreleaser configuration is validated during builds to avoid release build only failures.
3. This also leans on the signature of the goreleaser docker container to pin the artifact in a similar way to
terraform.
Hopefully these refinements can be also be used to improve other projects using goreleaser and buildkite.
=> Refactor to remove hard coded goreleaser architecture

CHANGELOG.md
=> Release 1.9.0 - Don't allow interpolations in signed steps input

CHANGELOG.md, buildkite/data_source_signed_pipeline_steps_test.go, go.mod, go.sum
for fix with escaped interpolations affecting signed pipelines data sources that have escaped interpolations that should be text e.g., regex
Related library update:
https://github.com/buildkite/interpolate/releases/tag/v0.1.3
=> SUP-2356: update interpolate version 

CHANGELOG.md, buildkite/resource_cluster_agent_token.go, buildkite/resource_cluster_default_queue.go, buildkite/resource_cluster_queue.go
Agent Tokens and (Default) Queues cannot be moved between Clusters so any attempt via Terraform should force the Resources to be replaced if the Cluster ID changes.
=> SUP-2495: Update Resources to be replaced if Cluster ID changes

CHANGELOG.md, buildkite/data_source_pipeline_template_test.go
Fix(Pipeline Template datasource): Corrected attribute checks against created pipeline template datasources within its tests. The tests were previously checking the resource attributes for both of the `id` and `name` variants, which have been corrected.
=> SUP-2536: Asserting pipeline template datasource attributes on its tests

buildkite/generated.go
Raising results from `50` -> `100` to address issue: https://github.com/buildkite/terraform-provider-buildkite/issues/566
=> Increase cluster queues returned in API response

buildkite/resource_cluster_queue.go
Instead of raising an error, raise a warning and remove the missing resource from state when not in results from API.
Issue: https://github.com/buildkite/terraform-provider-buildkite/issues/567
=> Remove cluster queues from state if not included in API response

CHANGELOG.md, buildkite/resource_organization_rule.go, buildkite/resource_organization_rule_test.go
Bug/Fix(Organization rules resource/): A quick amendment with an inclusive test case for `buildkite_organization_rule` resources not to `panic` when trying to update a rule in its current form.
The provider will now relay the diagnostic error that was surfaced before panicking, and thus presenting that to applies of such deltas.
I've added a test that creates a rule with all attributes (`configAllCustomDescription`), then tries to update the `description` of that created rule, which will be caught by regex and pass accordingly.
=> SUP-2774: Stop panicking on organization rule updates

.github/CODEOWNERS
to make it easier to manage the CODEOWNERS externally rather than needing to create PRs to update the file
=> chore: update CODEOWNERS to GitHub Team

CHANGELOG.md, buildkite/resource_cluster_default_queue.go, buildkite/resource_cluster_queue.go, buildkite/resource_cluster_queue_test.go
* removed `isPausible` as it would trigger Pausing when the Description was updated and State `DispatchedPaused = false`
* compare Plan and State values to pause/resume dispatch else do nothing, which stops changes to the `Description` causing the Queue to be paused
* `r.ClusterQueueUpdate.ClusterQueue.DispatchPaused` is nil at the time of the original logic resulting in `panic: runtime error: invalid memory address or nil pointer dereference` so changed to the Plan Value to be used for clarity else could be hardcoded as `state.DispatchPaused = types.BoolValue(true)` or `state.DispatchPaused = types.BoolValue(false)` (where appropritate)
* Remove error raised when a Cluster Queue doesn't have a Default Queue defined as there is an error with the API when updating a Queue resulting it in …
=> SUP-2813: correct logic for pausing/resuming Dispatch on Queues and remove error with Default Cluster Queues

buildkite/resource_cluster_queue.go
* Queues cannot change from Self-Hosted to Hosted (and vice-versa) so Resource should be recreated
* instance_shape cannot be updated in-place so Resource should be recreated to change it
=> SUP-2591: add PlanModifiers when Hosted Agent attributes changed

CHANGELOG.md, buildkite/resource_cluster_queue.go
Initially the `Update` would only capture and update the state by checking if state already existed, which meant that if no linux or mac configuration was provided in the create, it would never be stored in an update (an `agent_image_ref` couldn't be added to an existing queue).
This fix is to validate against the plan, setting the state appropriately as the plan generated it.
I also updated the `CHANGELOG.md` to clean up the past few PRs.
=> Fix state management on updating the hosted_agents configuration of a cluster queue

buildkite/resource_pipeline.go, buildkite/resource_pipeline_test.go, docs/resources/pipeline.md, internal/planmodifier/use_derived_pipeline_slug.go
Changes `slug` from a read-only attribute to an optional configurable attribute. If not set, `slug` is derived from the pipeline name and returned from the API. The `slug` will be updated when the `name` of the pipeline changes. If the `slug` is defined, a second REST API call is made to update the `slug` for the pipeline. The `slug` can be set or excluded at any time in the pipeline's lifecycle and the value will be set based on the user-defined input or via the API's response.
Utilizes Terraform [private state](https://developer.hashicorp.com/terraform/plugin/framework/resources/private-state) to track whether `slug` value in State was set via `api` or `user`. This extra value is required to correctly evaluate the transition of removing user-defined `slug` from an existing resource and …
=> SUP-2777 - Allow configurable pipeline slugs

buildkite/data_source_signed_pipeline_steps.go, buildkite/data_source_signed_pipeline_steps_test.go
We changed from using `SignPipeline()` to using `SignSteps()` with `go-pipeline` for signed pipeline steps. Need to also pass `env` as `Options` when calling `SignSteps()` to ensure they are included with `signed_fields`.
=> Ensure global `env` are signed with steps

buildkite/resource_pipeline.go, buildkite/resource_pipeline_test.go, docs/resources/pipeline.md, internal/planmodifier/use_derived_pipeline_slug.go
Reverts the changes to `provider_settings` brought in via PR https://github.com/buildkite/terraform-provider-buildkite/pull/607 and released in version [v1.15.5](https://github.com/buildkite/terraform-provider-buildkite/releases/tag/v1.15.5). Will revisit `provider_settings` management at a later time when additional functionality is enabled in our GraphQL API.
Keeps the fixes implemented to ensure the `slug` attribute is correctly reconciled with state, whether user-defined or derived from the API.
=> SUP-3241 - Revert explicit default `provider_settings`, keep fixes to `slug` logic

buildkite/resource_cluster_queue.go
Fixes https://github.com/buildkite/terraform-provider-buildkite/issues/866
Also ensures that the value of `XcodeVersion` stored in state is sourced from the API response vs. what was provided via the plan. This was covering up another issue where the `XcodeVersion` was not actually being set via the API.
=> SUP-3317 - Fix hosted agent attributes state mismatch

CHANGELOG.md, docs/resources/cluster_queue.md, examples/resources/buildkite_cluster_queue/resource.tf
Fix (Hosted Linux cluster queue resource docs/example): Small fix for the `buildkite_cluster_queue` Linux variety example to be named accordingly
=> Fix: Hosted Linux cluster queue resource example / docs alignment

.goreleaser.yml
- As per https://goreleaser.com/deprecations/#changelogskip, we should use `disable: true` instead of `skip: true` in the `changelog` section of the Go Releaser config file
=> chore: use disable: true for changelog

buildkite/generated.go, buildkite/graphql/cluster_queue.graphql, buildkite/graphql/registry.graphql
The fix applied in https://github.com/buildkite/terraform-provider-buildkite/issues/566 was not included in the `.graphql` file so it was reverted on the next genqlient re-generation.
Also fixed the `GetRegistryID()` query to define `slug` as `ID`, in alignment with our schema. Regenerated genqlient code after fixing.
=> Update cluster queue results, fix registry arguments

Dockerfile, Makefile, buildkite/resource_test_suite_team_test.go, buildkite/resource_test_suite_test.go, docker-compose.yml
chore: actually support parallelism
- just setting `t.Parallel()` doesn't mean tests run in parallel
- sets the `-parallel` flag to test commands
=> chore: enable parallelism

buildkite/generated.go, buildkite/graphql/cluster_queue.graphql, buildkite/resource_cluster_queue.go
Instead of `agentImageRef` and `xcodeVersion` being set to `null` for create/update mutations, allow `platformSettings.linux` and `platformSettings.macos` to be set to `null` and have genqlient omit them when not set.
This fix now fully resolves https://github.com/buildkite/terraform-provider-buildkite/issues/869, where https://github.com/buildkite/terraform-provider-buildkite/pull/898 only fixed the issue when an Organization had the `Feature::BUILDKITE_HOSTED_AGENTS_BASE_IMAGE_URL` feature enabled.
=> Set Hosted Agent OS shapes to `null` for `cluster_queue`, use `omitempty` to align with GQL processing

internal/planmodifier/use_derived_pipeline_slug.go
Addresses a condition where private state to manage `slug` attribute source does not exist AND `slug` is a user-defined attribute.
Fixes https://github.com/buildkite/terraform-provider-buildkite/issues/903
=> Extra logic around missing private state

README.md, lefthook.yml
Run `make docs` as pre-commit hook, so we have nice and fresh docs.
=> chore: add make docs to pre-commit hooks

buildkite/data_source_cluster_test.go
- Skips a flaky test on the cluster datasource
- This test is constantly causing CI to fail and doesn't add that much value
=> Skip flaky cluster timeout test

buildkite/resource_pipeline.go
Ensure that a pipeline's `color` argument is either `null` or valid hex color format (`#abc123`). The GQL mutations to create/update a pipeline will return `null` if an empty string (`""`) is provided for the `color` field. Setting this validation on the TF argument will eliminate having to transform the plan (converting `""` -> `null`) in order to handle data inconsistencies.
=> Validate pipeline color as hex color format

Dockerfile, buildkite/data_source_pipeline.go, buildkite/generated.go, buildkite/graphql/pipeline.graphql, buildkite/resource_pipeline.go, buildkite/resource_pipeline_test.go, docs/data-sources/pipeline.md, docs/resources/pipeline.md
* Add `cluster_name` attribute to `buildkite_pipeline` resource
* Add `cluster_id` attribute to `buildkite_pipeline` data source
* Add `cluster_name` attribute to `buildkite_pipeline` data source
* Switch from `public.ecr.aws` to Docker registry to avoid `429 Too Many Requests - Server message: toomanyrequests: Data limit exceeded` errors from `hosted` queue
=> Add cluster attributes to pipeline resource, data source

buildkite/resource_pipeline.go, docs/resources/pipeline.md
Document `filter_condition` expected behavior, and emit warning when `filter_condition` is set alongside `trigger_mode` `none` or undefined.  `filter_condition` would be only applied when `trigger_mode` is set to `code`.
=> fix: update documentation for filter condition and trigger mode

buildkite/resource_pipeline.go, buildkite/util.go, buildkite/util_test.go
Add retry mechanism for pipeline deletion when active jobs prevent immediate deletion.
To adjust timeout for `delete` operations, adjust `delete` attribute in `timeouts` settings for the provider – https://registry.terraform.io/providers/buildkite/buildkite/latest/docs#delete-1, example:
```HCL
provider "buildkite" {
organization = "my-magic-org"
timeouts = {
delete = "10m"
}
}
```
___
Expected output during `terraform apply` when deleting pipeline resource(s):
```
buildkite_pipeline.test: Still destroying... [id=UGlwZWxpbmUtLS0wMTk3YzVmMC1lM2QxLTQyYzItYmI5NS0xZWYzNTg4NDg3ZTE=, 08m00s elapsed]
buildkite_pipeline.test: Destruction complete after 8m8s
```
Closes #504
=> feat(pipeline): add retry logic for delete with active jobs

buildkite/resource_cluster_queue.go, tf-proj/main.tf
Now that we have the updated graph to include the new shapes, we also need to bring these through to the provider to use.
I've brought the internal naming inline with the Linux shapes, with the addition of the `M4` to differentiate specifically with macOS.
Also updated the `tf-proj/` with better defaults and valid config for the new macOS capabilities.
=> Ensure new macOS shapes are actually usable

buildkite/resource_cluster_queue.go, docs/resources/cluster_queue.md
Per [CHANGELOG](https://buildkite.com/resources/changelog/293-mac-hosted-agents-now-running-on-m4-pro-hardware/) M4 Shapes will supersede M2 Shapes so updating the docs to add such information.
=> SUP-4151: Add description for instance_shape with deprecation notice 

buildkite/resource_pipeline.go, internal/planmodifier/use_derived_pipeline_slug.go
The additional comparison between plan and state for `slug` is unnecessary during updates. This was resulting in the `slug` becoming derived from the pipeline name during updates and leaving `slug` value in state as user-defined. Also removed an unnecessary condition in the `planmodifier` used to evaluate user- vs. api-defined `slug` attribute.
Fixes https://github.com/buildkite/terraform-provider-buildkite/issues/954
=> Fix wrong `slug` value set during pipeline updates

.buildkite/pipeline.release.yml, .buildkite/pipeline.yml
Follow on from the work to support session tags in https://github.com/buildkite-plugins/aws-assume-role-with-web-identity-buildkite-plugin/pull/18
Requires matching update to the IAM role in PR: https://github.com/buildkite/aws-buildkite-dev/pull/471
=> Update to use OIDC session tokens on AWS role assumption

buildkite/resource_cluster_queue.go, buildkite/resource_cluster_queue_test.go, docs/resources/cluster_queue.md, examples/resources/buildkite_cluster_queue/resource.tf
**CREATED AS DRAFT TO BE MERGED AFTER 31 JULY 2025**
Per [CHANGELOG](https://buildkite.com/resources/changelog/293-mac-hosted-agents-now-running-on-m4-pro-hardware/) M2 Instances Shapes have been superseded and no longer valid so removing them and updating docs.
Will need to be rebased as based as Built upon changes from https://github.com/buildkite/terraform-provider-buildkite/pull/952
=> SUP-4151: Remove deprecated Mac Instance shapes

buildkite/generated.go, buildkite/graphql/cluster_queue.graphql, buildkite/resource_cluster_queue.go, buildkite/resource_cluster_queue_test.go
Instead of matching the cluster queue to the returned queues of a cluster, use the ID for a Node GQL query.
=> Switch `buildkite_cluster_queue` Read() func to use Node ID

CHANGELOG.md
Adds the following PR's to the Changelog for version v1.24.0:
- Improve default team handling for pipeline resource by @JoeColeman95 in https://github.com/buildkite/terraform-provider-buildkite/pull/969
- New data sources - buildkite_clusters, buildkite_teams by @petetomasik in https://github.com/buildkite/terraform-provider-buildkite/pull/971
- Switch buildkite_cluster_queue read to use Node ID by @petetomasik in https://github.com/buildkite/terraform-provider-buildkite/pull/972
=> Adding v1.24.0 to Changelog

CHANGELOG.md, buildkite/data_source_registry.go, buildkite/data_source_registry_test.go, buildkite/resource_agent_token_test.go, buildkite/resource_cluster_agent_token_test.go, buildkite/resource_cluster_queue_test.go, buildkite/resource_cluster_test.go, buildkite/resource_pipeline.go, buildkite/resource_pipeline_schedule_test.go, buildkite/resource_pipeline_template_test.go, buildkite/resource_pipeline_test.go, buildkite/resource_team_member_test.go, buildkite/resource_team_test.go, buildkite/resource_test_suite_test.go, buildkite/util.go, go.mod, go.sum
Reverts buildkite/terraform-provider-buildkite#975
There's been some very valid discussion that this change brings up other issues;
- Do we do this for everything?
- Other providers don't do this; the AWS provider errors on `apply`
- The error will still only happen on `apply` if you don't have sufficient permissions to view the original pipeline
- Does the last one create permission/security concern where intentionally not allowing a user to see a pipeline will confirm the pipeline exists at `plan`
=> Revert "warn on plan for duplicate pipeline name"
